"""
Metadron Capital — SQLAlchemy ORM table definitions.

Tables
------
- Flow          : named orchestration flows
- FlowRun       : individual executions of a flow
- Trade         : trades generated by a flow run
- ApiKey        : hashed API keys for authentication
- Portfolio     : point-in-time portfolio snapshots
"""

import logging
from datetime import datetime, timezone

logger = logging.getLogger("metadron.models")

try:
    from sqlalchemy import (
        Boolean,
        Column,
        DateTime,
        Float,
        ForeignKey,
        Integer,
        String,
        Text,
    )
    from sqlalchemy.orm import relationship
except ImportError:
    raise RuntimeError(
        "SQLAlchemy is required. Install it with: pip install sqlalchemy"
    )

from engine.db.database import Base


def _utcnow():
    """Return the current UTC timestamp (timezone-aware)."""
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# Flow
# ---------------------------------------------------------------------------
class Flow(Base):
    """A named orchestration flow (e.g. 'Daily Alpha Pipeline')."""

    __tablename__ = "flows"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    name = Column(String(256), nullable=False)
    description = Column(Text, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    status = Column(String(32), default="active")

    runs = relationship("FlowRun", back_populates="flow", cascade="all, delete-orphan")


# ---------------------------------------------------------------------------
# FlowRun
# ---------------------------------------------------------------------------
class FlowRun(Base):
    """A single execution of a Flow."""

    __tablename__ = "flow_runs"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    flow_id = Column(Integer, ForeignKey("flows.id"), nullable=False)
    started_at = Column(DateTime, default=_utcnow)
    completed_at = Column(DateTime, nullable=True)
    result_json = Column(Text, nullable=True)
    status = Column(String(32), default="pending")

    flow = relationship("Flow", back_populates="runs")
    trades = relationship("Trade", back_populates="flow_run", cascade="all, delete-orphan")


# ---------------------------------------------------------------------------
# Trade
# ---------------------------------------------------------------------------
class Trade(Base):
    """An individual trade generated by a flow run."""

    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    flow_run_id = Column(Integer, ForeignKey("flow_runs.id"), nullable=False)
    ticker = Column(String(16), nullable=False)
    side = Column(String(8), nullable=False)  # "buy" | "sell"
    quantity = Column(Float, nullable=False)
    price = Column(Float, nullable=False)
    signal_type = Column(String(64), nullable=True)
    timestamp = Column(DateTime, default=_utcnow)

    flow_run = relationship("FlowRun", back_populates="trades")


# ---------------------------------------------------------------------------
# ApiKey
# ---------------------------------------------------------------------------
class ApiKey(Base):
    """Hashed API key for authenticating external consumers."""

    __tablename__ = "api_keys"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    key_hash = Column(String(256), nullable=False, unique=True)
    name = Column(String(128), nullable=False)
    created_at = Column(DateTime, default=_utcnow)
    is_active = Column(Boolean, default=True)


# ---------------------------------------------------------------------------
# Portfolio
# ---------------------------------------------------------------------------
class Portfolio(Base):
    """Point-in-time snapshot of portfolio state."""

    __tablename__ = "portfolios"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    nav = Column(Float, nullable=False)
    cash = Column(Float, nullable=False)
    gross_exposure = Column(Float, nullable=False)
    net_exposure = Column(Float, nullable=False)
    timestamp = Column(DateTime, default=_utcnow)
